= Validator 

image:https://badges.gitter.im/latitude-oss-validator/Lobby.svg[link="https://gitter.im/latitude-oss-validator/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"] image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[link="https://opensource.org/licenses/Apache-2.0"]

Validator defines a straigthforward Java api and a meta-model for business validation.

Data validation is a very common task that often is scattered in many different layers of an application. Some times the same validation criteria are implemented more than once, this can be time consuming and error-prone.

== Modules

There are more modules in the project, below a quick overview:

* *validator-core* - the library that provides core features.
* *validator-spring-autoconfigure* - integrates the core library in a *SpringFramework* IOC container.  

== Requirements

*Java 6* or later is required.

== Releases

Releases can be found in the https://github.com/latitude-oss/validator/releases[Github releases tab].

== Links

* https://github.com/latitude-oss/validator[Project page]
* https://github.com/latitude-oss/validator/issues[Issue tracking]

== License

Validator is Open Source software released under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
